apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCVXeEsn4e2uBclmx7vKirK6b/OmvvFspHvx8sMS7yWKurhFp6ASOSOEk9L1o1yYEbEAwb7Aa0dMiBh79ASPZS/EiEDAnKX/TnZrwQJoloUeQ32x4UmzhPImkUdobZH07hsuy/bjEGBIYCf971GjkDmIDnmr3Qn9fldu2HNKQQ9PcI6uHADyIXDH+/cO8MpnBG9vnptg1UjvEWpBrUCjEakO4iYOk2RiiLNJyW/C9+KVilL51ye3NuHuj448W1ZQjraz4/OTxzU9vQ5mKS7d7ZpPgk+Ay1vk4/evs4f5tfTbhcei9CMfV7VHPTvHjMu7y518CYtl6gin7hv69y6wEyrpq1wHa5mAs1IKNTgda21VWpKSJARFRSiVe8bZgqHXrWle4wQ6JNz6oGWEGqKKhx39zBgasVfGGOZJ6jdVKqNTh6T3HGkaBYC5fEzNRtwPVZsuSFbCjckeaW9n+FAxEvwXl95tP8den8ROH3SpUUHNqEnGZGXvAqmHLbVz5nJOvbIMtRxd6eG0N0X92wKWECq3qZuF7uV42jMZdFRoh7+IuFR+dUIbJyVIzifBWQMvG7TedFjS6oG5BIPwmGlUUQYgAaalnO1n2WErzAdSSGDmWt5SGjwzUcPty3Ig+2K1DIk3lrqsIglYraAtrZc5UIdusdl8xrxcTorUhD5ssUsns4j8IeRjItAtqrnBUE0eTejGoYNfaZ4EmnAuLE8NQGTkIFWo2j9k0LX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

