apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:bxq9e3jLkfUyqVWSaa0PyRNzBvfBYg7Llg==,iv:m8R4GKIHfkVRlTz3vJGuBuPjRCvWlWzY0Xh5CHI36AU=,tag:Ep2YKsoITQESD4UxG9psyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-01T20:57:53Z"
    mac: ENC[AES256_GCM,data:war50M/B+nX0sYJsm/qRPemp/MDcu28vLg+K/zf1GUnjtMjX4iEc+9gsraWzcQMuQZ0Rnef9UN2Grn60Z/2YcobduDMfoyBUl6VIVgn2zkAmb2NI9I4pJuBeFw+ougP70N2iwilmm67aVVdGbJPqJ3mOBGFmU3e0W6VN4VIhkQU=,iv:7keUk77ahgqTEWLYHvCzanKqTJ14cr007qmUcmx18Q0=,tag:IxIG2HEsFzK5/+w6RYCUmA==,type:str]
    pgp:
        - created_at: "2023-03-01T20:57:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8G1FdRXaOQ8AQv/VlZiHv/GYv8ByeFDFHrk6uKL5+i2UwI9KrZtqsf/qB5k
            s+gG5QfoenuBnPd9Uc/J1/kGOJ2TICC7TycH/W9p0Dvm+5oN/YDkvS9JlSzyOMfs
            M0DmHSwtmhxIUcCyNEmUDIBZ8B/Wa1eTiFcE4hx1wtaO32rE870Zl/6bNejPHa21
            Fljol184OPRxO9gRqfd6SjDwJZbW6AStDoXX67tcr03bMPqCJ/pM7LFhC8SGAo07
            MJ/PvLsnM18OIfDKeod3V85ruM2PbSfTiUPluphGE2cYQG2QjJKpdVEJGrx+xoJk
            jlr75gIpiFzdcrCnj8lSPEBVdk9m8gj4BSBVskZftoZMCTd5HDdyBfEgQy4ETOFD
            H29omtpRee0tgImwTDTaRO3wpZQoNhRpxz914HqabAkJgY0DHFh0ocljBJ789Yhg
            mSAnTNyueF2fXOaLaygSJOlYBL2mOI04sik2dBiqcYR2smAcjucwiyM3RcM4r0Dv
            zpGeHz8qxCI5UvhHgdxt0lwBPh2jZDoINs74YRu3IeBziVD3LaYocnuJ5asV0gf1
            TIWKQYFLqTNeOoXWdAnu4TSfhWJZ1hVlQV942OfBtbykp5tZCMhqJgRlFfdLOiVf
            BgyEOlP7uw0jeU9u7g==
            =m6HC
            -----END PGP MESSAGE-----
          fp: BA413DF90E102503
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
